image:
  repository: ghcr.io/apradillo597/hello-api
  tag: "bb0fa8a15ac82c2df8d611ec8ee9a5d72f45ddbc"
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: ClusterIP
  port: 80
resources:
  requests: {cpu: "100m", memory: "128Mi"}
  limits: {cpu: "300m", memory: "256Mi"}
env:
  APP_VERSION: "ghcr"
