apiVersion: apps/v1
kind: Deployment
metadata:
name: {{ include "hello-api.fullname" . }}
labels:
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
spec:
replicas: {{ .Values.replicaCount }}
selector:
matchLabels:
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
strategy:
type: RollingUpdate
template:
metadata:
labels:
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
spec:
{{- if .Values.image.imagePullSecrets }}
imagePullSecrets:
{{- toYaml .Values.image.imagePullSecrets | nindent 8 }}
{{- end }}
containers:
- name: app
image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
imagePullPolicy: {{ .Values.image.pullPolicy }}
ports:
- containerPort: 3000
env:
- name: APP_VERSION
value: {{ .Values.env.APP_VERSION | quote }}
readinessProbe:
httpGet: { path: "/", port: 3000 }
initialDelaySeconds: 3
periodSeconds: 5
livenessProbe:
httpGet: { path: "/", port: 3000 }
initialDelaySeconds: 10
periodSeconds: 10
resources:
{{- toYaml .Values.resources | nindent 12 }}