apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/apradillo597/Argocd.git
    targetRevision: main
    path: canary             # 👈 carpeta nueva que vamos a crear
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
