apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: monitoring
  labels:
    release: monitoring   # 👈 MUY IMPORTANTE: que coincida con el nombre del chart
spec:
  selector:
    matchLabels:
      app: podinfo
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
