name: ci
on:
push:
branches: ["main"]
pull_request:


jobs:
build-and-push:
runs-on: ubuntu-latest
permissions:
contents: read
packages: write # para GHCR
steps:
- uses: actions/checkout@v4


- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v3


- name: Login to GHCR
uses: docker/login-action@v3
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}


- name: Build and push
uses: docker/build-push-action@v6
with:
context: .
file: ./Dockerfile
push: true
tags: |
ghcr.io/${{ github.repository_owner }}/hello-api:${{ github.sha }}
ghcr.io/${{ github.repository_owner }}/hello-api:dev
cache-from: type=gha
cache-to: type=gha,mode=max


- name: Run tests
run: |
npm --prefix app ci
npm --prefix app test