name: ci
on:
  push:
    branches: ["main"]
  pull_request: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instala deps de forma tolerante: usa 'ci' si hay lockfile; si no, 'install'
      - name: Install deps
        run: |
          if [ -f app/package-lock.json ]; then
            npm ci --prefix app
          else
            npm install --prefix app
          fi

      - name: Run tests
        run: npm --prefix app test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hello-api:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/hello-api:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Bump Helm image.tag to current SHA
        if: github.ref == 'refs/heads/main'
        run: |
          sudo curl -L -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq -i '.image.tag = strenv(GITHUB_SHA)' chart/values.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add chart/values.yaml
          git commit -m "ci: bump image.tag to ${GITHUB_SHA}" || echo "No changes"
          git push origin HEAD:main

    
